services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8123:8123
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    tmpfs:
      - /var/lib/clickhouse:size=1G
      - /var/log/clickhouse-server:size=100M
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    ports:
      - 8474:8474
      # Open several ports so tests can each create an isolated proxy.
      - 8475-8480:8475-8480
