on:
  workflow_dispatch:

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:22.8.13.20-alpine
        ports:
          - 8123:8123
        env:
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.3"
          otp-version: "25.2.3"

      - run: elixir mix_install/bench_select.exs
      - run: elixir mix_install/bench_insert.exs
